name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Make the production plugin bundle
        run: |
          yarn
          yarn build
      - name: Perform Github Release
        uses: softprops/action-gh-release@v1
        with:
          name: bb-select
          tag_name: bb-select